### ISSUE TITLE
add caption

### ISSUE THREAD

**Issue by spostad7** [ArtDesignCreativeStudio/artdesign-slider#1]
tanx for your excellent work
is it possible to have some captions in slider!? and how about animating captions!?

**Comment by ArtDesignCreativeStudio** [comment]
This function will be added in the next release - after about a month - two :)

**Comment by spostad7** [comment]
tanx! it will be great!

**Comment by ArtDesignCreativeStudio** [comment]
spostad7, try new version (2.1.0) - ArtDesignSlider now with Captions with 9 transition effects!

**Comment by spostad7** [comment]
awesooooooooome! like a charm! 
tanx a lot
