### ISSUE TITLE
How to assign a particular effect (transition)?

### ISSUE THREAD

**Issue by avconsbn** [ArtDesignCreativeStudio/artdesign-slider#4]
How to assign a particular effect (transition)?
------
).ArtDesignSlider({
			EffectsAndSpeed: {
				Name: "BlindsVerticalTopBottomSlideToRight",
				AnimationFx: "easeOutBack",
				Speed: 600,
				Percent: 8,
				Delay: 100
			},
			AutoStart: false
------
 It does not work!

**Comment by ArtDesignCreativeStudio** [comment]
AutoStart: false - tested!

If you want only two effects (or tree etc):

```js
$("#ArtDesignSlider").ArtDesignSlider({
        AutoStart: false,
        AnimationEffectsAndSpeed: [
            {
                Name: "BlindsVerticalFadeToRight",
                Speed: 600,
                Percent: 6,
                Delay: 100
            },
            {
                Name: "BlindsVerticalFadeToLeft",
                Speed: 600,
                Percent: 6,
                Delay: 100
            }
        ]
});
```

If you want to setup any image with custom effect:

```html
<div id="ArtDesignSlider" class="DemoSlider">
        <ul>
              <li data-slider-animation-effect="BlindsVerticalFadeToRight">
                     <img src="path/to/1.jpg" alt="Image 1" data-slider-animation-effect="BlindsVerticalFadeToRight">
              </li>
              <li data-slider-animation-effect="BlindsVerticalFadeToRight">
                     <img src="path/to/2.jpg" alt="Image 2" data-slider-animation-effect="BlindsVerticalFadeToLeft">
              </li>
        </ul>
</div>
```

**Comment by avconsbn** [comment]
Thank you, it works!
How to start the desired effect (once), when the page loads?
) .ArtDesignSlider (). GoTo (2); - Starts a standard (normal) Fade.

**Comment by ArtDesignCreativeStudio** [comment]
If you want ArtDesignSlider start from Image 2:

```js
$("#ArtDesignSlider").ArtDesignSlider({
 StartImage: 2
});
```

If you want use function GoTo():
```js
window.ArtDesignSlider = $("#ArtDesignSlider").ArtDesignSlider();

then 

window.ArtDesignSlider.GoTo(2);
```

**Comment by avconsbn** [comment]
StartImage: 2 - it works!

How to start the desired effect (once), when the page loads???
Thank you

**Comment by avconsbn** [comment]
window.ArtDesignSlider = $("#ArtDesignSlider").ArtDesignSlider();
then 
window.ArtDesignSlider.GoTo(2);

It does not work!
It shows the first (!!) image. + transition, when the page loads!

**Comment by ArtDesignCreativeStudio** [comment]
When the slider start - the first image loaded directly without animation.The first image not start with fade - all slider start with fade (main container).

window.ArtDesignSlider.GoTo() is a External function. With GoTo() you can move slider position to aхy image anytime.

**Comment by avconsbn** [comment]
How to (possibly?) change the effect at the start of the slider (main container)? Fade to change the Blind.

- all slider start with fade (main container).
to change
- all slider start with Blind (main container).
possibly?

**Comment by ArtDesignCreativeStudio** [comment]
Consistently set AnimationEffects:
```js
$("#ArtDesignSlider").ArtDesignSlider({
        AnimationEffectsAndSpeed: [
            {
                Name: "BlindsVerticalFadeToLeft",  //#1
                Speed: 600,
                Percent: 6,
                Delay: 100
            },
            {
                Name: "BlindsVerticalFadeToRight", #2
                Speed: 600,
                Percent: 6,
                Delay: 100
            }
        ]
});
```

**Comment by avconsbn** [comment]
MouseWheel Hover (Over slide) listing (flips through, toggle) slides. How to prevent (false)?
Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
```js
$("#ArtDesignSlider").ArtDesignSlider({
        ListenMouseWheel: false, //disable MouseWheel
        ListenKeysPress: false      // disable KeysPress
});
```

**Comment by avconsbn** [comment]
How to prevent (false) Overlays-files?
Overlays\01.png-15.png
Thank you.

**Comment by avconsbn** [comment]
How to assign - autoHeight: true?
SliderHeight Default: 400
If you assign a different value - Responsive (for Height) is not working! Only Width. Height remains Constant!

SliderWidth: "100%",
SliderWidthUnit: "%",
SliderHeight: "100%", \\This does not work!
SliderHeightUnit: "%",

SliderHeight: "100%" - Collapses (not show) slider. (This CSS rule.)

**Comment by avconsbn** [comment]
Overlay - understood!
Overlay: "Overlays/06.png", \\ Default
Overlay: false, \\ to prevent Overlays

**Comment by ArtDesignCreativeStudio** [comment]
```js
$("#ArtDesignSlider").ArtDesignSlider({
     Overlay: "", 
     SliderWidth: "100",
     SliderWidthUnit: "%",
     SliderHeight: "100",
     SliderHeightUnit: "%",
});
```
SliderHeight 100% work - try demo:
http://www.artdesign-jquery.com/Examples/ArtDesignSlider/FullWidth1.html

**Comment by avconsbn** [comment]
CMS Joomla 3.4.1 + Modul Menu (Standart)
How bind slides ArtDesignSlider - with change to the menu?
Get the (created) a nice menu! Click on Menu item - images change with the transition.
Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
You can use ArtDesignSlider External functions - GoTo(1, 2 etc), GoToNext(), GoToPrev()

```js
window.ArtDesignSlider = $("#ArtDesignSlider").ArtDesignSlider();

function Prev() {
    window.ArtDesignSlider.GoToPrev();
}
function Next() {
    window.ArtDesignSlider.GoToNext();
}
function GoTo() {
    window.ArtDesignSlider.GoTo(4);
}
```

**Comment by avconsbn** [comment]
function GoTo () - the right decision.
I do not have enough programming knowledge to do it.
CMS Joomla 3.4.1 - no direct access to menu items. They are stored in an array. Output - Rendered in loop (foreach) in Modul Menu (file helper.php). Attached standard Modul Menu
http://rusfolder.com/43741710

**Comment by avconsbn** [comment]
SliderHeight: "100," It works!
Earlier, I made a syntax error (SliderHeight: "100%").

SliderWidthUnit: "px",
SliderHeightUnit: "px",
In this case - Responsive decreases with decreasing Width of the browser window.
But! Height remains Constant!
Is it possible to reduce the height? Proportionally?
This 100% Responsive Width + Height.
It - autoHeight.
Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
About Height - link or JS Bin demo?

**Comment by avconsbn** [comment]
link
http://www.artdesign-jquery.com/Examples/ArtDesignSlider/FullWidth1.html 
Reduce the width of the browser.
Width Slider - is reduced.
But! Height remains Constant!

How to assign - autoHeight? 
Possible?
The height is adjusted depending on the width.
Sample:
http://philparsons.co.uk/demos/box-slider/

**Comment by ArtDesignCreativeStudio** [comment]
Height not Constant! Height = window.height().
In ArtDesignSlider Width and Height are independent of one another!

**Comment by avconsbn** [comment]
Is it possible to make dependent on Height Width?

**Comment by ArtDesignCreativeStudio** [comment]
Yes, but you need to change code (plugin).

**Comment by avconsbn** [comment]
...dependent on Height Width. Very useful options!
...need to change code (plugin).
You will change in the next release?
When?

**Comment by avconsbn** [comment]
$("#ArtDesignSlider").ArtDesignSlider({
 StartImage: 2
});
When the page is loaded - switches to the image 2. The code works.

window.ArtDesignSlider = $("#ArtDesignSlider").ArtDesignSlider();
window.ArtDesignSlider.GoTo(2);
When the page is loaded - switches to the image 1. (No error.) however - The code is not working!!
How to fix?
Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
GoTo is an external function you can use this function with any events (click, hover etc.)

**Comment by ArtDesignCreativeStudio** [comment]
```js
window.ArtDesignSlider = $("#ArtDesignSlider").ArtDesignSlider();
setTimeout(function() {
window.ArtDesignSlider.GoTo(2);
}, 6000);
```
After 6 sec ArtDesignSlider go to position 2.

**Comment by avconsbn** [comment]
Awesome! Works !!
The transition occurs always on the first slide to the specified.
GoTo (2) 1 -> 2
GoTo (3) 1 -> 3
GoTo (4) 1 -> 4
etc
Is it possible to make the transition from the active slide (current) to the selected new?
Example:
Active 2, GoTo (4) 2 -> 4 (instead of 1 -> 4)

setTimeout. Less than 100 is not running. Possible to reduce, for example up to 10 or 0?
Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
Is it possible to make the transition from the active slide (current) to the selected new?
- If active image is 2 (all 5):
2->1 //+
2->2 //- 
2->3 //+ 
2->4 //+ 
2->5 //+
You can use custom transition for all images:
```js
<div id="ArtDesignSlider">
        <ul>
              <li data-slider-animation-effect="BlindsVerticalFadeToLeft">
                     <img src="path/to/1.jpg" alt="Image 1" >
              </li>
              <li data-slider-animation-effect="BlindsVerticalFadeToRight">
                     <img src="path/to/2.jpg" alt="Image 2">
              </li>
        </ul>
</div>
```

setTimeout. Less than 100 is not running. 
- This is because FirstInitializeFadeSpeed: 750 /view settings/

**Comment by avconsbn** [comment]
transition 
I asked another.
Images!
GoTo (2) 1 -> 2
GoTo (3) 1 -> 3
GoTo (4) 1 -> 4
etc

Example:
Active Image 2,
GoTo (4) 2 -> 4. From Images 2 to Images 4 (instead From Images 1 -> to Images 4).

Thank you.

**Comment by ArtDesignCreativeStudio** [comment]
With GoTo() you can move position to any image. Active image does not matter!
